name: Hyperion CI/PR Builds
run-name: |
  ${{ github.event_name == 'push' && '🌱 Push build -' || '' }}
  ${{ github.event_name == 'pull_request' && format('📦 Artifacts build for PR {0} - {1}', github.event.pull_request.number, github.event.pull_request.title) || github.event.head_commit.message }}

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:

  # GitHub Push/Pull Request (Release only on tagged commits)
  github_build:
    name: Qt ${{ matrix.qt_version }} Build ${{ matrix.qt_version == '6' && '(Testing))' || '' }}
    strategy:
      fail-fast: false
      matrix:
        qt_version: ['5', '6']
    uses: ./.github/workflows/qt5_6.yml
    secrets: inherit
    with:
      qt_version: ${{ matrix.qt_version }}
      event_name: ${{ github.event_name }}
      pull_request_number: ${{ github.event.pull_request.number }}
      publish: ${{ startsWith(github.event.ref, 'refs/tags') && matrix.qt_version == '5' }}

